services:
  backend:
    profiles: [ "deploy" ]
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend/alembic:/alembic
    depends_on:
      - database
    ports:
      - "${BE_PORT_EXTERNAL}:${BE_PORT}"
    env_file:
      - .env

  database:
    profiles: [ "deploy" ]
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"

  frontend:
    profiles: [ "deploy" ]
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FE_PORT_EXTERNAL}:${FE_PORT}"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/package-lock.json:/app/package-lock.json:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - /app/node_modules
    stdin_open: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  pgadmin:
    profiles: [ "deploy" ]
    image: dpage/pgadmin4:7
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:80"

#  backend_test:
#    profiles: [ "test" ]
#    build:
#      context: .
#      dockerfile: backend/Dockerfile.test
#    container_name: backend_test
#    env_file:
#      - .env.test
#    depends_on:
#      - database_test
#
#  database_test:
#    profiles: [ "test" ]
#    image: postgres:16
#    container_name: database_test
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    env_file:
#      - .env.test

volumes:
  db_data:
